### ISSUE TITLE
Text is cut in render.WrappedText

### ISSUE THREAD

**Issue by LukiLeu** [tidbyt/pixlet#135]
The text in a render.WrappedText is cut if the parameter `linespacing` is used and no heigth is provided.

![sbb_timetable](https://user-images.githubusercontent.com/3243291/151716330-d6903e5a-69c0-4c80-99dc-39c2507a9647.gif)

The above image is generated with this code:
```
def display_error(msg):
    return render.Root(
        child = render.Row(
            children = [
                render.Box(
                    width = 20, 
                    height = 32, 
                    color = "#000", 
                    child = render.Image(
                        src = ERROR_ICON, 
                        width = 16, 
                        height = 16
                    )
                ),
                render.Box(
                    padding = 0, 
                    width = 44, 
                    height = 32, 
                    child = 
                    render.WrappedText(
                        content = msg, 
                        color = "#FFF", 
                        linespacing = 1,                        
                        font = FONT_TO_USE
                    )
                ),
            ],
        ),
    )
```

If the linespacing is removed, the text is rendered correctly.
![sbb_timetable](https://user-images.githubusercontent.com/3243291/151716393-1c5debac-4303-4711-925a-8df87c99ae6d.gif)

**Comment by LukiLeu** [comment]
Hi @vlauffer
Thanks for your response. I was aware of the height parameter, and I agree with you that it works with that parameter. And as you suggested, with some padding, one might get also the centering correct.
However, this approach does not solve the bug that produces the erroneus output. While your approach works, it still requires manual fine tuning. I would therefore say, your approach is a workaround until that bug is fixed.

**Comment by vlauffer** [comment]
@LukiLeu just realized you mentioned the height parameter in the very first sentence of the original post (facepalm) my bad. I see what you mean now though. I'm pretty interested in finding out why the text gets cut off without a set height, and why setting height relocates the text to the top instead of center...

I'm very new to Go and Starlark but I'm gonna try to figure out why this happens. 

adding these links here incase I lose them:

[wrappedtext doc](https://github.com/tidbyt/pixlet/blob/main/render/wrappedtext.go
), [DrawStringWrapped function](https://github.com/fogleman/gg/blob/v1.3.0/context.go#L755), [font metrics](https://pkg.go.dev/golang.org/x/image/font#Metrics
)

**Comment by LukiLeu** [comment]
My guess is, that the linespacing is not added to an internal calculated height and only the bare height of the font multiplied with the nunber of lines is used
