### ISSUE TITLE
[BUG] - Watch option throws error

### ISSUE THREAD

**Issue by sethomas** [tidbyt/pixlet#82]
When using the `--watch` option, after a file save, I get the below error:
```
pixlet serve --watch ./helloworld.star 
2021/12/19 13:06:48 loaded ./helloworld.star
2021/12/19 13:06:48 listening at http://127.0.0.1:8080
2021/12/19 13:06:48 error establishing a new connection websocket: request origin not allowed by Upgrader.CheckOrigin
2021/12/19 13:06:53 detected updates for ./helloworld.star, reloading
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x9531a6]

goroutine 52 [running]:
github.com/gorilla/websocket.(*Conn).beginMessage(0x0, 0xc000182330, 0x1, 0xc000149f10, 0x411d70)
	/root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:472 +0x26
github.com/gorilla/websocket.(*Conn).NextWriter(0x0, 0x1, 0x7f2a842540a0, 0x8, 0x10, 0x7f2aae7c77d0)
	/root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:513 +0x53
github.com/gorilla/websocket.(*Conn).WriteJSON(0x0, 0xa42b80, 0xc00061e1b0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/json.go:24 +0x49
tidbyt.dev/pixlet/server.(*Server).fileWatcher(0xc0000ab400, 0x0)
	/buildkite/builds/buildkite-agent-1-1/tidbyt/release-pixlet/server/server.go:210 +0x28a
created by tidbyt.dev/pixlet/server.(*Server).serveWebsocket
	/buildkite/builds/buildkite-agent-1-1/tidbyt/release-pixlet/server/server.go:82 +0x15a


```

## Details
 - `pixlet` binary `v0.7.0`
 - Ubuntu 21.10 x86_64
 - GNOME 40.5 via gnome-terminal
 
## To replicate:
1) Make a file called `helloworld.star` with the below contents:
```py
load("render.star", "render")
def main():
    return render.Root(
        child = render.Text("Hello, World!!")
    )
```
2) download `pixlet` binary and run the below command:
```
pixlet serve --watch ./helloworld.star
```
3) save a file and see the error noted above.

## Side note:
This product and the launch and the dev options are AMAZING, huge kudos to the team, I am loving this device.

**Comment by betterengineering** [comment]
Hey @sethomas! So sorry you're experiencing this issue. I've definitely seen this pop up on occasion in practice, but i'm unable to reproduce the error now. If I had to guess, the error is because we're trying to write to a websocket that's no longer valid (or potentially was never valid). Which would make sense because we never check if the connection is alive or implement any of the websocket ping/pong messages to keep the connection open.

As it were, we are in the process of overhauling this section of the code base to make it a lot more robust, including proper connection handling. Could you give #86 a try if you have a chance and let me know if it resolves your issues?

**Comment by betterengineering** [comment]
I believe this should be resolved. If #86 did not resolve this issue, please feel free to comment below and I'll investigate further and reopen this issue.

**Comment by sethomas** [comment]
@betterengineering sorry for delay! I tried out `v0.8.2` and all is well with `--watch` working! Thank you again and congrats on such a cool product!
