### ISSUE TITLE
App Cycle Speed Options

### ISSUE THREAD

**Issue by joeyhoer** [tidbyt/pixlet#92]
![IMG_1102](https://user-images.githubusercontent.com/739656/147512380-f081b136-1b63-4d95-9a29-05d76a7ed52c.jpg)

Not sure if this is the right place for this; it would be sweet if there was an option to disable app cycling (or set app cycling to "manual").

**Use case:** I created a clock app which renders a `webp` with 1440 frames (one for each minute of the day). If I push this to the Tidbyt, it should be able to run indefinitely and keep time semi-accurately (assuming the `webp` frame delay timing is correct). However, what I've noticed is that even when this is the only app which is installed on the Tidbyt, the Tidbyt still resets it to the first frame after some number of seconds. I believe this is due to the app "cycling" which resets the `webp` to the first frame—this effectively prevents an all day clock from being created via a single push. (The alternative is to push a new image every minute.)

**Suggested behavior:** I believe an ideal situation would be to allow users to specify a preferred number of seconds to display an app before cycling. Then, an additional checkbox would exist which would say something like "Allow apps to set their own cycle timing"; setting this checkbox to true, would allow each app to control the amount of time they are displayed before cycling; if no cycle timing is defined by the app, it would fallback to the user's preference.

Additionally, when only one app is installed, it should not cycle, as doing so resets the animation.

**Comment by betterengineering** [comment]
Hey @joeyhoer, thanks for the issue! I certainly wouldn't try to render a full days worth of frames to display a custom clock, although I'd be pretty interested if the time drift was noticeable or if it would be significantly off by the end of the day. Check out https://github.com/tidbyt/pixlet/issues/89#issuecomment-1003739990 for a better approach.

App cycle speed options defined by the applet is something we're currently looking into but it's going to be a pretty big change. It would be required for things like stock or sports tickers where a lot of information is displayed for a lot longer than 15 seconds in a ticker style. Even something like the news app would benefit from being able to define how long the story was so it wasn't cut short going to the next app.

We are looking to support something like this but don't currently have a timeframe for when it will be available. I'm going to close this issue for now since it's not immediately actionable, but please feel free to reach back out with a new issue or community discussion if you have more questions.
