### ISSUE TITLE
Missing documentation: encoding images to base64

### ISSUE THREAD

**Issue by Eastonco** [tidbyt/pixlet#94]
## Img -> base64
After reading over the [bitcoin tutorial](https://github.com/tidbyt/pixlet/blob/main/doc/tutorial.md), I noticed there were a few missing pieces. Primarily, how to convert your image to a base64 to then be decoded by the library. I found an [website](https://www.base64encode.org/) that seemed to do the trick but I ended up getting errors when I tried to server the generated webp file. Can you provide further information of your process for conversion?

## Recommended size of pixel art
Obviously this was able to be inferred based on the size and dimensions of the provided bitcoin logo however further documentation and recommendations on optimal pixel art image sizing would be a helpful addition to the documentation.

**Comment by drudge** [comment]
On macOS, I use the `base64` command in Terminal like this:

```sh
> base64 path/to/file.png | pbcopy
```

The base64 encoded file contents will be copied to your clipboard ready to be pasted in to your .star script.

**Comment by rohansingh** [comment]
@drudge That's exactly how I do it as well. Though I also use `fold` to make the output a bit more manageable:

```
base64 some-file.png | fold | pbcopy
```

That adds a new linebreak every 80 characters.

**Comment by betterengineering** [comment]
Hi @Eastonco,

Thanks for the issue! I'm not in love with the idea that we base64 encode blobs and stick them into starlark. That is the current pattern that most folks (including us internally) follow but I wouldn't call it the blessed approach. Ideally we'd have some way to load in an asset directory and be able to reference those files. I'm hesitant to document it simply because it would encourage a pattern that needs to be resolved. I'm going to close this for now, @drudge and @rohansingh have some good examples to get you started. Feel free to comment below with any issues you experience and I'll be more then happy to help you out.
